name: Test Polaris Catalog
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the DuckDB-Iceberg artifact to download"
        required: true
        type: string

jobs:
  test-polaris:
    name: Test against Polaris Catalog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Download DuckDB-Iceberg artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: build/release

      - name: Restore permissions
        run: |
          find ./build/release -type f -name 'duckdb*' -exec chmod +x {} \;
          find ./build/release -type f -name 'unittest*' -exec chmod +x {} \;

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install Polaris dependencies
        run: |
          sudo apt update -y -qq
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo apt install -y -qq python3-venv

      - name: Setup Polaris
        run: |
          make polaris

      - name: Run Polaris Specific Tests
        env:
          POLARIS_SERVER_AVAILABLE: 1
        run: |
          export POLARIS_CLIENT_ID=$(cat polaris_client_id.txt)
          export POLARIS_CLIENT_SECRET=$(cat polaris_client_secret.txt)
          ./build/release/test/unittest "$PWD/test/*" --list-test-names-only || true
          ./build/release/test/unittest "$PWD/test/*"

      - name: Run Generic IRC tests
        env:
          ICEBERG_SERVER_AVAILABLE: 1
          SECRETS_CREATED_AND_CATALOG_ATTACHED: 1
        run: |
          export POLARIS_CLIENT_ID=$(cat polaris_client_id.txt)
          export POLARIS_CLIENT_SECRET=$(cat polaris_client_secret.txt)
          ./build/release/test/unittest "$PWD/test/sql/local/irc_any_catalog/*" --list-test-names-only || true
          ./build/release/test/unittest "$PWD/test/sql/local/irc_any_catalog/*" --test-config test/configs/polaris.json  --autoloading available

      - name: Upload Polaris Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: polaris-server-logs
          path: |
            polaris_catalog/polaris-server.log
            polaris_catalog/polaris-error.log
          if-no-files-found: ignore