name: Test Nessie Reusable
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the DuckDB-Iceberg artifact to download"
        required: true
        type: string

jobs:
  test-nessie:
    name: Test against Nessie Catalog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Download DuckDB-Iceberg artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: build/release

      - name: Restore permissions
        run: |
          find ./build/release -type f -name 'duckdb*' -exec chmod +x {} \;
          find ./build/release -type f -name 'unittest*' -exec chmod +x {} \;

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Install Nessie dependencies
        run: |
          sudo apt update -y -qq
          sudo apt install -y -qq python3-venv

      - name: GitHub machine compatibility
        working-directory: nessie/docker
        run: |
          # replace $ with $$ in all healthcheck lines, otherwise there are interpolation errors
          # on github machines for some reason
          sed -i '/healthcheck/,/]/ s/\$/$$/g' catalog-auth-s3/docker-compose.yml
          # lower client timeouts because they cannot be longer than realm timeouts.
          # all client timeouts are 86400 right now
          sed -i 's/86400/1800/g' authn-keycloak/config/iceberg-realm.json

      - name: Install required python packages
        run: |
          make nessie_start

      - name: Run Nessie Specific Tests
        env:
          NESSIE_SERVER_AVAILABLE: 1
        run: |
          ./build/release/test/unittest "$PWD/test/sql/local/irc_specific_catalogs/nessie/*" --list-test-names-only || true
          ./build/release/test/unittest "$PWD/test/sql/local/irc_specific_catalogs/nessie/*"

      - name: Generate data
        run: |
          make nessie_data

      - name: Run Generic IRC tests
        env:
          ICEBERG_SERVER_AVAILABLE: 1
          SECRETS_CREATED_AND_CATALOG_ATTACHED: 1
        run: |
          ./build/release/test/unittest "$PWD/test/sql/local/irc_any_catalog/*" --list-test-names-only || true
          ./build/release/test/unittest "$PWD/test/sql/local/irc_any_catalog/*" --test-config test/configs/nessie.json  --autoloading available
